import turtle
wn = turtle.Screen()
wn.bgcolor("lightblue")

#alex = turtle.Turtle()
#alex.forward(150)
#alex.left(90)
#alex.forward(100)
#alex.left(90)
#alex.forward(150)
#alex.left(90)
#alex.forward(100)

#milo = turtle.Turtle()
#milo.forward(180)
#milo.left(90)
#milo.forward(250)
#milo.left(90)
#milo.forward(180)
#milo.left(90)
#milo.forward(250)

#ajax = turtle.Turtle()
#ajax.forward(100)
#ajax.left(45)
#ajax.forward(50)
#ajax.left(135)
#ajax.forward(100)
#ajax.left(45)
#ajax.forward(50)

#delta = turtle.Turtle()
#delta.circle(33)
#delta.circle(49.5)

#beta = turtle.Turtle()
#beta.backward(150)
#beta.right(90)
#beta.forward(50)

charlie = turtle.Turtle()
charlie.forward(50)
charlie.backward(100)
charlie.forward(50)
charlie.right(90)
charlie.forward(150)
charlie.right(90)
charlie.forward(50)
charlie.backward(100)
